initial changes for db setup and connecting ec2_1

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -36,28 +36,32 @@ jobs:
     - name: Install necessary tools on EC2
       run: |
         # SSH into EC2 and install tools
-          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
-            # Update system and install required packages
-            sudo yum update -y
-            sudo yum groupinstall "Development Tools" -y
-            sudo yum install -y python3-devel unixODBC-devel
+        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
+          # Update system and install required packages
+          sudo yum update -y
+          sudo yum groupinstall "Development Tools" -y
+          sudo yum install -y python3-devel unixODBC-devel
 
-            # Remove any existing Microsoft repo and add the new one
-            sudo rm -f /etc/yum.repos.d/microsoft.repo
-            sudo curl https://packages.microsoft.com/config/rhel/7/prod.repo -o /etc/yum.repos.d/microsoft.repo
+          # Remove any existing Microsoft repo and add the new one
+          sudo rm -f /etc/yum.repos.d/microsoft.repo
+          sudo curl https://packages.microsoft.com/config/rhel/7/prod.repo -o /etc/yum.repos.d/microsoft.repo
 
-            # Install the ODBC Driver 17 for SQL Server
-            sudo yum install -y msodbcsql17 --assumeyes
+          # Try installing ODBC Driver 17 for SQL Server non-interactively with yum
+          sudo yum install -y msodbcsql17 --assumeyes
+
+          # If yum fails, fall back to RPM with --noscripts
+          if [ $? -ne 0 ]; then
+            echo "YUM installation failed, falling back to RPM..."
             sudo rpm -ivh --noscripts msodbcsql17-17.10.6.1-1.x86_64.rpm
-            
+          fi
 
-            # Install Python pip and dependencies from requirements.txt
-            pip3 install --upgrade pip
-            pip3 install -r /home/ec2-user/booking_system/requirements.txt
+          # Install Python pip and dependencies from requirements.txt
+          pip3 install --upgrade pip
+          pip3 install -r /home/ec2-user/booking_system/requirements.txt
 
-            # Echo success message
-            echo "ODBC Driver 17 for SQL Server and pip dependencies installed successfully"
-          EOF
+          # Echo success message
+          echo "ODBC Driver 17 for SQL Server and pip dependencies installed successfully"
+        EOF
 
     - name: Upload files to EC2 using rsync
       run: |
